# Build Options
#   change to "no" to disable the options, or define them in the Makefile in 
#   the appropriate keymap folder that will get included automatically
#
BOOTMAGIC_ENABLE  = no       # Virtual DIP switch configuration(+1000)
MOUSEKEY_ENABLE   = yes      # Mouse keys(+4700)
EXTRAKEY_ENABLE   = yes      # Audio control and System control(+450)
CONSOLE_ENABLE    = yes      # Console for debug(+400)
COMMAND_ENABLE    = yes      # Commands for debug and configuration
DEBUG_ENABLE      = yes
SLEEP_LED_ENABLE  = no       # Breathing sleep LED during USB suspend
NKRO_ENABLE       = yes      # USB Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
UNICODE_ENABLE    = yes      # Unicode.
ONEHAND_ENABLE    = yes      # Allow swapping hands of keyboard
BLUETOOTH_ENABLE  = no       # Enable Bluetooth with the Adafruit EZ-Key HID

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
